In [29]:
import numpy as np

In [30]:
#NP Array: This method creates a new NumPy array

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [31]:
#Arrange: This method creates a sequence of numbers in a NumPy array

a = np.arange(0, 10, 2)  # start, stop, step
print(a)

[0 2 4 6 8]


In [32]:
#Reshape: This method reshapes a NumPy array

a = np.array([1, 2, 3, 4, 5, 6])
b = np.reshape(a, (2, 3)) #rows, columns
print(b)

[[1 2 3]
 [4 5 6]]


In [33]:
#Zero:  This method creates a NumPy array filled with zeros

a = np.zeros((2, 3)) #rows, columns
print(a)

#Same with np.ones()

[[0. 0. 0.]
 [0. 0. 0.]]


In [34]:
#Max: This method returns the maximum value in a NumPy array

a = np.array([1, 2, 3, 4, 5])
b = np.max(a)
print(b)

5


In [35]:
#Min: This method returns the minimum value in a NumPy array

a = np.array([1, 2, 3, 4, 5])
b = np.min(a)
print(b)

1
